name: Android CI WiFi Salvavidas

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - uses: android-actions/setup-android@v3

    - name: Create gradlew
      run: |
        gradle wrapper --gradle-version 8.5 --distribution-type bin
        chmod +x gradlew

    - name: Generar Keystore
      run: |
        keytool -genkey -v \
          -keystore app/wifisalvavidas.jks \
          -alias wifisalvavidas \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -dname "CN=Gustavo Garay, OU=Altea-Garay, O=Altea-Garay, L=Garcia, S=Nuevo Leon, C=MX"

    - name: Build Release AAB
      run: ./gradlew bundleRelease --stacktrace

    - name: Sign AAB
      run: |
        jarsigner -verbose \
          -sigalg SHA256withRSA \
          -digestalg SHA-256 \
          -keystore app/wifisalvavidas.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/bundle/release/app-release.aab \
          wifisalvavidas

    - name: Subir AAB
      uses: actions/upload-artifact@v4
      with:
        name: WiFi-Salvavidas-AAB
        path: app/build/outputs/bundle/release/app-release.aab
