name: Android CI WiFi Salvavidas

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - uses: android-actions/setup-android@v3

    - name: Create gradlew
      run: |
        gradle wrapper --gradle-version 8.5 --distribution-type bin
        chmod +x gradlew

    - name: Generar Keystore
      run: |
        keytool -genkey -v \
          -keystore app/wifisalvavidas.jks \
          -alias wifisalvavidas \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -dname "CN=Gustavo Garay, OU=Altea-Garay, O=Altea-Garay, L=Garcia, S=Nuevo Leon, C=MX"

    - name: Build Release APK and AAB
      run: ./gradlew assembleRelease bundleRelease --stacktrace

    - name: Sign APK (Esquema V2/V3 para Android Moderno)
      run: |
        # Usamos apksigner para que el celular reconozca la firma oficial
        $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks app/wifisalvavidas.jks \
          --ks-key-alias wifisalvavidas \
          --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --out app/build/outputs/apk/release/WiFi-Salvavidas-FINAL.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Sign AAB
      run: |
        jarsigner -verbose \
          -sigalg SHA256withRSA \
          -digestalg SHA-256 \
          -keystore app/wifisalvavidas.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/bundle/release/app-release.aab \
          wifisalvavidas

    - name: Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: WiFi-Salvavidas-APK-Instalador
        path: app/build/outputs/apk/release/WiFi-Salvavidas-FINAL.apk

    - name: Subir AAB
      uses: actions/upload-artifact@v4
      with:
        name: WiFi-Salvavidas-AAB-Tienda
        path: app/build/outputs/bundle/release/app-release.aab
